name = "Cat Modpack"
author = "quack95, wineclub27"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f676fa21a1f09e8d8e7d95b11228c968d6883b279853cc83cf13bcfc3557b07"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks/"
