name = "Cat Modpack"
author = "quack95, wineclub27"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e35166b132d29e48766f0d6081b1cd0abbc80f9cad73c4148c01c482d0999f3"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks/"
