name = "Cat Modpack"
author = "quack95, wineclub27"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff94d209a32e23329c158946321cc4c814de72d915c2470f71eaf6bacadb39e5"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks/"
